@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueTagList
AddressBook *-right-> "1" UniqueDeliveryList
UniqueTagList -[hidden]down- UniquePersonList
UniqueTagList -[hidden]down- UniquePersonList
UniqueDeliveryList -[hidden]up- UniquePersonList
UniqueDeliveryList -[hidden]up- AddressBook

UniqueTagList -right-> "*" Tag
UniqueDeliveryList -right-> "*" Delivery
UniquePersonList -right-> Person
Delivery -[hidden]up- UniquePersonList

Person -up-> "*" Tag
Person "1" -up-> "0..1" Delivery

Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Address
@enduml
