@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindDeliveryCommandParser" as FindDeliveryCommandParser LOGIC_COLOR
participant "fdc:FindDeliveryCommand" as FindDeliveryCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "p:DeliveryDatePredicate" as DeliveryDatePredicate MODEL_COLOR
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find-delivery dt/2026-04-01")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("find-delivery dt/2026-04-01")
activate AddressBookParser

create FindDeliveryCommandParser
AddressBookParser -> FindDeliveryCommandParser
activate FindDeliveryCommandParser

FindDeliveryCommandParser --> AddressBookParser
deactivate FindDeliveryCommandParser

AddressBookParser -> FindDeliveryCommandParser : parse("dt/2026-04-01")
activate FindDeliveryCommandParser

create DeliveryDatePredicate
FindDeliveryCommandParser -> DeliveryDatePredicate : DeliveryDatePredicate("2026-04-01")
activate DeliveryDatePredicate

DeliveryDatePredicate --> FindDeliveryCommandParser : p
deactivate DeliveryDatePredicate

create FindDeliveryCommand
FindDeliveryCommandParser -> FindDeliveryCommand : FindDeliveryCommand(p)
activate FindDeliveryCommand

FindDeliveryCommand --> FindDeliveryCommandParser :
deactivate FindDeliveryCommand

FindDeliveryCommandParser --> AddressBookParser : fdc
deactivate FindDeliveryCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindDeliveryCommandParser -[hidden]-> AddressBookParser
destroy FindDeliveryCommandParser

AddressBookParser --> LogicManager : fdc
deactivate AddressBookParser

LogicManager -> FindDeliveryCommand : execute(m)
activate FindDeliveryCommand

FindDeliveryCommand -> Model : updateFilteredPersonList(p)
activate Model

Model --> FindDeliveryCommand
deactivate Model

create CommandResult
FindDeliveryCommand -> CommandResult
activate CommandResult

CommandResult --> FindDeliveryCommand
deactivate CommandResult

FindDeliveryCommand --> LogicManager : r
deactivate FindDeliveryCommand

[<--LogicManager
deactivate LogicManager
@enduml
