@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":RescheduleCommandParser" as RescheduleCommandParser LOGIC_COLOR
participant "rc:RescheduleCommand" as RescheduleCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "rd:RescheduleDeliveryDescriptor" as RescheduleDescriptor MODEL_COLOR
participant "updated:Person" as UpdatedPerson MODEL_COLOR
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("reschedule 1 tm/14:00")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("reschedule 1 tm/14:00")
activate AddressBookParser

create RescheduleCommandParser
AddressBookParser -> RescheduleCommandParser
activate RescheduleCommandParser

RescheduleCommandParser --> AddressBookParser
deactivate RescheduleCommandParser

AddressBookParser -> RescheduleCommandParser : parse("1 tm/14:00")
activate RescheduleCommandParser

create RescheduleDescriptor
RescheduleCommandParser -> RescheduleDescriptor
activate RescheduleDescriptor

RescheduleDescriptor --> RescheduleCommandParser
deactivate RescheduleDescriptor
create RescheduleCommand
RescheduleCommandParser -> RescheduleCommand: RescheduleCommand(index, rd)
activate RescheduleCommand

RescheduleCommand --> RescheduleCommandParser :
deactivate RescheduleCommand

RescheduleCommandParser --> AddressBookParser : rc
deactivate RescheduleCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
RescheduleCommandParser -[hidden]-> AddressBookParser
destroy RescheduleCommandParser

AddressBookParser --> LogicManager : rc
deactivate AddressBookParser

LogicManager -> RescheduleCommand : execute(m)

activate RescheduleCommand
RescheduleCommand -> RescheduleCommand: createRescheduledPerson(targetPerson, rd)
activate RescheduleCommand

create UpdatedPerson
RescheduleCommand -> UpdatedPerson
activate UpdatedPerson
UpdatedPerson --> RescheduleCommand
deactivate UpdatedPerson

RescheduleCommand --> RescheduleCommand: updated
deactivate RescheduleCommand

RescheduleCommand -> Model : setPerson(targetPerson, updated)
activate Model

deactivate Model

RescheduleCommand -> Model : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
activate Model

deactivate Model

create CommandResult
RescheduleCommand -> CommandResult
activate CommandResult

CommandResult --> RescheduleCommand
deactivate CommandResult

RescheduleCommand --> LogicManager : r
deactivate RescheduleCommand

[<--LogicManager
deactivate LogicManager
@enduml
